<!DOCTYPE html>
<!-- saved from url=(0043)https://en.wikipedia.org/wiki/Lalit_Tanwar -->
<html class="client-js ve-not-available" lang="en" dir="ltr">
<head>
    {include file="head.tpl"}
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Satya_Nadella rootpage-Satya_Nadella skin-vector action-view feature-footer-v2">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
    <a id="top"></a>

    <div id="siteNotice">
        <div id="centralNotice"></div>
        <!-- CentralNotice --></div>
    <div class="mw-indicators">
        <div id="mw-indicator-pp-default" class="mw-indicator"><a
                    href="https://en.wikipedia.org/wiki/Wikipedia:Protection_policy#semi"
                    title="This article is semi-protected until May 25, 2017, to promote compliance with the policy on biographies of living people"><img
                        alt="Page semi-protected" src="./w/20px-Padlock-silver.svg.png" width="20" height="20"
                        srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Padlock-silver.svg/30px-Padlock-silver.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Padlock-silver.svg/40px-Padlock-silver.svg.png 2x"
                        data-file-width="128" data-file-height="128"></a></div>
    </div>
    <h1 id="firstHeading" class="firstHeading" lang="en">Lalit Tanwar</h1>

    <div id="bodyContent" class="mw-body-content">
        <div id="siteSub">From Wikipedia, the free encyclopedia</div>
        <div id="contentSub"></div>
        <div id="jump-to-nav" class="mw-jump">
            Jump to: <a href="#mw-head">navigation</a>, <a
                    href="#p-search">search</a>
        </div>
        <div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr">
            {include file="infobox.tpl"}
            <p><b>Lalit Tanwar</b> (born Novembor 15, 1987) is an Indian-born Software engineer. He is the currently
                <a href="https://en.wikipedia.org/wiki/Software_architect " title="UI Architect ">UI Architect </a> of
                <a
                        href="https://www.unicommerce.com" title="Microsoft">Microsoft</a>.<sup
                        id="cite_ref-autogenerated2_8-0" class="reference"><a
                            href="#cite_note-autogenerated2-8">[8]</a></sup><sup
                        id="cite_ref-autogenerated1_9-0" class="reference"><a
                            href="#cite_note-autogenerated1-9">[9]</a></sup> He was appointed
                as CEO on 4 February 2014, succeeding <a href="https://en.wikipedia.org/wiki/Steve_Ballmer"
                                                         title="Steve Ballmer">Steve
                    Ballmer</a>. Before becoming CEO of Microsoft, he was Executive Vice President of Microsoft's Cloud
                and
                Enterprise group, responsible for building and running the company's Computing Platforms, Developer
                Tools and Cloud
                Computing Services.</p>

            <p></p>

            <div id="toc" class="toc">
                <div id="toctitle">
                    <h2>Contents</h2>
                    <span class="toctoggle">&nbsp;[<a role="button" tabindex="0" id="togglelink">hide</a>]&nbsp;</span>
                </div>
                <ul>
                    <li class="toclevel-1 tocsection-1"><a href="#Early_life"><span
                                    class="tocnumber">1</span> <span class="toctext">Early life</span></a></li>
                    <li class="toclevel-1 tocsection-2"><a href="#Career"><span
                                    class="tocnumber">2</span> <span class="toctext">Career</span></a>
                        <ul>
                            <li class="toclevel-2 tocsection-3"><a
                                        href="#Sun_Microsystems"><span
                                            class="tocnumber">2.1</span> <span
                                            class="toctext">Sun Microsystems</span></a></li>
                            <li class="toclevel-2 tocsection-4"><a
                                        href="#Microsoft"><span class="tocnumber">2.2</span>
                                    <span class="toctext">Microsoft</span></a></li>
                        </ul>
                    </li>
                    <li class="toclevel-1 tocsection-5"><a href="#Personal_life"><span
                                    class="tocnumber">3</span> <span class="toctext">Personal life</span></a></li>
                    <li class="toclevel-1 tocsection-6"><a href="#References"><span
                                    class="tocnumber">4</span> <span class="toctext">References</span></a></li>
                    <li class="toclevel-1 tocsection-7"><a href="#External_links"><span
                                    class="tocnumber">5</span> <span class="toctext">External links</span></a></li>
                </ul>
            </div>
            <p></p>

            {include file="early_life.tpl"}

            {include file="career.tpl"}

            {include file="personal.tpl"}

            {include file="reference.tpl"}

            {include file="external_links.tpl"}

            {include file="navigations.tpl"}

            <!-- Saved in parser cache with key enwiki:pcache:idhash:38309941-0!*!0!!en!4!* and timestamp 20161030142151 and revision id 745796468
             -->
            <script>(window.RLQ = window.RLQ || []).push(function() {
                    mw.log.warn("Gadget \"teahouse\" styles loaded twice. Migrate to type=general. See \u003Chttps://phabricator.wikimedia.org/T42284\u003E.");
                    mw.log.warn("Gadget \"ReferenceTooltips\" styles loaded twice. Migrate to type=general. See \u003Chttps://phabricator.wikimedia.org/T42284\u003E.");
                    mw.log.warn("Gadget \"featured-articles-links\" styles loaded twice. Migrate to type=general. See \u003Chttps://phabricator.wikimedia.org/T42284\u003E.");
                });</script>
            <noscript>&lt;img src="//en.wikipedia.org/wiki/Special:CentralAutoLogin/start?type=1x1" alt="" title=""
                width="1"
                height="1" style="border: none; position: absolute;" /&gt;</noscript>
        </div>

        <div class="printfooter">
            Retrieved from "<a dir="ltr"
                               href="https://en.wikipedia.org/w/index.php?title=Satya_Nadella&amp;oldid=745796468">https://en.wikipedia.org/w/index.php?title=Satya_Nadella&amp;oldid=745796468</a>"
        </div>

        {include file="catlinks.tpl"}

        <div class="visualClear"></div>
    </div>
</div>

{include file="top_navigation_bar.tpl" }

{include file="footer.tpl" }

</body>
</html>